import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "YourRequestHasBeenSentToDrivers": "تم إرسال طلبك إلى السائقين",
          "Done": "تم",
          "MessageSentSuccessfully": "تم ارسال الرسالة بنجاح",
          "fail": "فشل",
          "PleaseLoginAgain": "الرجاء اعادة تسجيل الدخول",
          "Settings": "الإعدادات",
          "notifications": "الاشعارات",
          "requests": "طلباتي",
          "Main": "الرئيسية",
          "joinAs": "الأنضمام ك",
          "Client": "عميل",
          "Transporter": "الناقل",
          "CreateAnAccount": "إنشاء حساب",
          "Login": "! تسجيل دخول",
          "AlreadyHaveAnAccount": "هل لديك حساب؟",
          "fullName": "الاسم بالكامل",
          "mail": "البريد الالكتروني",
          "MobileNumber": "رقم الجوال",
          "password": "الرقم السري",
          "orRegisterWith": "أو التسجيل ب",
          "ReceivingLocation": ": مكان الاستلام",
          "deliveryLocation": ": موقع التسليم",
          "ChooseADate": "اختيار موعد",
          "DriverNotes": "ملحوظات السائق",
          "ApproximatePrice": "السعر التقريبي",
          "send": "ارسال",
          "bigTanker": "ناقلة كبيرة",
          "ChooseTheRightType": "إختر النوع المناسب",
          "TrillGermanSides": "تريله جوانب الماني",
          "curtainTrill": "تريله ستارة",
          "TrailerGallab": "تريله قلاب",
          "TrillingHighSides": "تريله جوانب مرتفعة",
          "trillItsSurface": "تريله سطحه",
          "waterTrill": "تريله ماء",
          "CarTransportTrailer": "تريله نقل سيارات",
          "TrailerForTransportingSheepAndLivestock": "تريله نقل أغنام و مواشي",
          "BradTrail": "تريله براد",
          "waterTank": "صهريج ماء",
          "AFuelTanker": "تريله نقل محروقات",
          "lorryTruck": "شاحنة لوري",
          "closedTruck": "شاحنة مغلقة",
          "DumpTruck": "شاحنة قلاب",
          "flatbedTruck": "شاحنة سطحة",
          "OtherBigVector": "ناقلات كبيرة أخرى",
          "refrigeratorTruck": "شاحنة براد",
          "back": "رجوع",
          "name": "اسم",
          "number":"رقم",
          "ContactTheDriver":"اتصل بالسائق",
          "SuggestAnotherPrice":"أقتراح سعر أخر",
          "CancellingOrder":"إلغاء الأمر",
          "AreYouSureToCancelTheOrder":"هل انت متأكد من إلغاء الطلب",
          "no":"لا",
          "yes":"نعم",
          "changeTheDriver":"تغيير السائق",
          "orderTracking":"تتبع الطلب",
          "FileAComplaint":"رفع شكوى",
          "TermsAndConditions":"الشروط و الأحكام",
          "OtherOffers":"عروض أخرى",
          "DearCustomer":"عزيزي العميل",
          "YouCannotCancelTheOrderOrReplaceTheRepresentativeAfter7MinutesFromNow":"لا يمكنك الغاء الطلب أو استبدال المندوب بعد 7 دقائق من الأن",
          "Cancellation":"الغاء",
          "OK":"موافق",
          "Acceptance":"قبول",
          "SuggestedPrice":"السعر المقترح",
          "adjustThePrice":"اضبط السعر",
          "YourPriceHasBeenAccepted":"تم قبول سعرك",
          "GoToThePaymentStep":"اذهب الى خطوة الدفع",
          "paying":"الدفع",
          "MyOrderDetails":" تفاصيل طلبي ",
          "NewApplicationPayAttentionToTheLocationOfDeliveryAndReceivingNewApplicationPayAttentionToTheSiteOfDeliveryAndReceiptNewApplicationPayAttentionToTheSiteOfDeliveryAndReceipt":"تطبيق جديد انتبه لموقع التسليم و الاستلام تطبيق جديد انتبه لموقع التسليم و الاستلام تطبيق جديد انتبه لموقع التسليم و الاستلام ",
          "IForgotTheSecretNumber":"نسيت الرقم السري",
          "PleaseEnterYourMobileNumberTo":"من فضلك قم بإدخال رقم الجوال الخاص بك الى",
          "LookingForATanker":"ابحث عن ناقلة",
          "LargeTankertrucksAndTrailers":"ناقلة كبيرة (شاحنات و تريلات )",
          "MediumTankerDyna":"ناقلة متوسطة (دينا)",
          "SmallCarrierParcelsAndServices":"ناقلة صغيرة (طرود و خدمات)",
          "SomeValuesEnteredAreEmptyPleaseMakeSureThatAllValuesAreEntered":"هناك بعض القيم المدخلة فارعة الرجاء التأكد من إدخال جميع القيم",
          "Entry":"دخول",
          "DontHaveAnAccount":"ليس لديك حساب؟",
          "orLoginWith":"أو الدخول ب",
          "mediumTanker":"ناقلة متوسطة",
          "myBalance":"رصيدي",
          "AddCreditVia":"اضافة رصيد عن طريق",
          "PreviousOrders":"الطلبات السابقة",
          "currentOrders":"الطلبات الحالية",
          "OrderDetails":"تفاصيل الطلب",
          "tracking":"تتبع",
          "chat":"دردشة",
          "Contact":"اتصال",
          "OrderNumber":"رقم الطلب",
          "ARequestHasBeenSentFromTheDriver":"تم ارسال طلب من السائق",
          "YourOrderDetails":"تفاصيل طلبك",
          "PaymentDetails":"تفاصيل الدفع",
          "cost":"التكلفة",
          "valueAddedTax":"15% ضريبة القيمة المضافة",
          "Total":"الإجمالي",
          "DriverName":"اسم السائق",
          "conveyorType":"نوع الناقل",
          "ApproximateArrivalTime":" : وقت الوصول التقريبي",
          "distance":" : المسافة",
          "VerifyPhoneNumber":"التحقق من رقم الهاتف",
          "EnterTheCodeSentTo":"أدخل الرمز المرسل إلى",
          "addCoupon":"أضافة كوبون",
          "PaymentMethod":"طريقة الدفع",
          "AddACreditDebitCard":"إضافة بطاقة  ائتمان / خصم",
          "cardNumber":"رقم البطاقة",
          "ExpiryDateMonthYear":"  تاريخ الإنتهاء                  شهر /سنة",
          "FirstName":"الاسم الأول",
          "lastName":"الاسم الأخير",
          "ourEnd":"!تهانينا",
          "PaymentConfirmedSuccessfully":"تم تأكيد الدفع بنجاح",
          "SaveTheCard":"حفظ البطاقة",
          "addCard":"أضافة بطاقة +",
          "cash":"نقدا",
          "Confirmation":"تأكيد  الطلب",
          "paid":"تم الدفع",
          "writeYourMessage":"اكتب رسالتك",
          "NotPaid":"لم يتم الدفع",
          "writeyourMessage":"اكتب رسالتك",
          "ComplaintsAndSuggestions":"الشكاوى و المقترحات",
          "WriteYourComplaintOrSuggestions":"اكتب شكواك او مقترحاتك",
          "WholesaleMerchandiseDelivery":"توصيل بضائع جملة",
          "FlowerDeliveryAndArrangement":"توصيل و تنسيق الزهور",
          "MiscellaneousOther":"متنوعة/ أخرى",
          "SweetsDelivery":"توصيل حلويات",
          "ShareTheApp":"مشاركة التطبيق",
          "Exit":"خروج",
          "LogOut":"تسجيل  خروج",
          "smallFridge":"براد صغير",
          "closedVan":"فان مغلق",
          "PersonnelServices":"خدمات المناديب",
          "tank":"دباب",
          "OtherSmallVectors":"ناقلات صغرى أخرى",
          "AwaitingPayment":"في انتظار الدفع",
          "WriteYourProblemDetailsHere":"اكتب تفاصيل مشكلتك هنا "
            "........................................"
            "..........................................."
            "..........................................."  "........................................"
            "..........................................."
            "..........................................." "..........................................."
            "................."  ".......",
          "attachments":"المرفقات",
          "YouCanUploadPhotos":"يمكنك رفع 3 صور"

        },
        "en": {
           "YourRequestHasBeenSentToDrivers": "Your request has been sent to drivers",
          "Done": "Done",
          "MessageSentSuccessfully": "Message sent successfully",
          "fail": "fail",
          "PleaseLoginAgain": "Please login again",
          "Settings": "Settings",
          "notifications": "notifications",
          "requests": "requests",
          "Main": "Main",
          "joinAs": "join as",
          "Client": "Client",
          "Transporter": "Transporter",
          "CreateAnAccount": "Create an account",
          "Login": "Login",
          "AlreadyHaveAnAccount": "do you have an account?",
          "fullName": "full name",
          "mail": "E-mail",
          "MobileNumber": "Mobile number",
          "password": "password",
          "orRegisterWith": "or register with",
          "ReceivingLocation": ": place of delivery",
          "deliveryLocation": ": delivery location",
          "ChooseADate": "Choose an appointment",
          "DriverNotes": "Driver's notes",
          "ApproximatePrice": "Approximate price",
          "send": "send",
          "bigTanker": "big tanker",
          "ChooseTheRightType": "Choose the right type",
          "TrillGermanSides": "Trill German sides",
          "curtainTrill": "curtain trill",
          "TrailerGallab": "Trailer Gallab",
          "TrillingHighSides": "Trill high sides",
          "trillItsSurface": "trill its surface",
          "waterTrill": "water trill",
          "CarTransportTrailer": "Car transport trailer",
          "TrailerForTransportingSheepAndLivestock": "Trailer for transporting sheep and livestock",
          "BradTrail": "Brad Trail",
          "waterTank": "water tank",
          "AFuelTanker": "A fuel tanker",
          "lorryTruck": "lorry truck",
          "closedTruck": "closed truck",
          "DumpTruck": "Dump truck",
          "flatbedTruck": "flatbed truck",
          "OtherBigVector": "Other large vector",
          "refrigeratorTruck": "refrigerator truck",
          "back": "back",
          "name": "name",
          "number":"number",
          "ContactTheDriver":"Call the driver",
          "SuggestAnotherPrice":"Suggest another price",
          "CancellingOrder":"Cancel",
          "AreYouSureToCancelTheOrder":"Are you sure to cancel the order",
          "no":"no",
          "yes":"yes",
          "changeTheDriver":"change the driver",
          "orderTracking":"order tracking",
          "FileAComplaint":"File a complaint",
          "TermsAndConditions":"Terms and Conditions",
          "OtherOffers":"Other offers",
          "DearCustomer":"Dear customer",
          "YouCannotCancelTheOrderOrReplaceTheRepresentativeAfter7MinutesFromNow":"You cannot cancel the order or replace the representative after 7 minutes from now",
          "Cancellation":"Cancellation",
          "OK":"OK",
          "Acceptance":"Acceptance",
          "SuggestedPrice":"Suggested price",
          "adjustThePrice":"Set the price",
          "YourPriceHasBeenAccepted":"Your price has been accepted",
          "GoToThePaymentStep":"Go to the payment step",
          "paying":"paying",
          "MyOrderDetails":" My order details",
          "NewApplicationPayAttentionToTheLocationOfDeliveryAndReceivingNewApplicationPayAttentionToTheSiteOfDeliveryAndReceiptNewApplicationPayAttentionToTheSiteOfDeliveryAndReceipt":"New application Pay attention to the location of delivery and receiving New application Pay attention to the site of delivery and receipt New application Pay attention to the site of delivery and receipt ",
          "IForgotTheSecretNumber":"I forgot the secret number",
          "PleaseEnterYourMobileNumberTo":"Please enter your mobile number to",
          "LookingForATanker":"Looking for a tanker",
          "LargeTankertrucksAndTrailers":"Large tanker (trucks and trailers)",
          "MediumTankerDyna":"Medium tanker (Dina)",
          "SmallCarrierParcelsAndServices":"Small carrier (parcels and services)",
          "SomeValuesEnteredAreEmptyPleaseMakeSureThatAllValuesAreEntered":"Some values entered are empty. Please make sure that all values are entered",
          "Entry":"Entry",
          "DontHaveAnAccount":"Don't have an account?",
          "orLoginWith":"or login with",
          "mediumTanker":"medium tanker",
          "myBalance":"my Balance",
          "AddCreditVia":"Add credit via",
          "PreviousOrders":"Previous orders",
          "currentOrders":"current orders",
          "OrderDetails":"Order details",
          "tracking":"tracking",
          "chat":"chat",
          "Contact":"Contact",
          "OrderNumber":"Order number",
          "ARequestHasBeenSentFromTheDriver":"A request has been sent from the driver",
          "YourOrderDetails":"Your order details",
          "PaymentDetails":"Payment details",
          "cost":"cost",
          "valueAddedTax":"15% VAT",
          "Total":"Total",
          "DriverName":"The driver's name",
          "conveyorType":"conveyor type",
          "ApproximateArrivalTime":": Approx. arrival time",
          "distance":" : distance",
          "VerifyPhoneNumber":"Verify phone number",
          "EnterTheCodeSentTo":"Enter the code sent to",
          "addCoupon":"add coupon",
          "PaymentMethod":"Payment method",
          "AddACreditDebitCard":"Add a credit/debit card",
          "cardNumber":"card number",
          "ExpiryDateMonthYear":"Expiry date            month/year",
          "FirstName":"First Name",
          "lastName":"last name",
          "ourEnd":"!our end",
          "PaymentConfirmedSuccessfully":"Payment confirmed successfully",
          "SaveTheCard":"Save the card",
          "addCard":"Add a card +",
          "cash":"cash",
          "Confirmation":"Confirmation",
          "paid":"paid",
          "writeYourMessage":"write your message",
          "NotPaid":"Not paid",
          "writeyourMessage":"write your message",
          "ComplaintsAndSuggestions":"Complaints and suggestions",
          "WriteYourComplaintOrSuggestions":"Write your complaint or suggestions",
          "WholesaleMerchandiseDelivery":"Wholesale merchandise delivery",
          "FlowerDeliveryAndArrangement":"Flower delivery and arrangement",
          "MiscellaneousOther":"Miscellaneous/ Other",
          "SweetsDelivery":"Sweets delivery",
          "ShareTheApp":"Share the app",
          "Exit":"Exit",
          "LogOut":"Log out",
          "smallFridge":"small fridge",
          "closedVan":"closed van",
          "PersonnelServices":"Personnel Services",
          "tank":"tank",
          "OtherSmallVectors":"Other small vectors",
          "AwaitingPayment":"Awaiting Payment",
          "WriteYourProblemDetailsHere":"Write your problem details here "
            "........................................"
            "..........................................."
            "..........................................."  "........................................"
            "..........................................."
            "..........................................." "..........................................."
            "................."  ".......",
          "attachments":"attachments",
          "YouCanUploadPhotos":"You can upload 3 photos"
        } ,
        "hi": {
           "YourRequestHasBeenSentToDrivers": "आपका अनुरोध ड्राइवरों को भेज दिया गया है",
          "Done": "पूर्ण",
          "MessageSentSuccessfully": "संदेश सफलतापूर्वक भेजा जा चुका है",
          "fail": "विफल",
          "PleaseLoginAgain": "कृपया फिर भाग लें",
          "Settings": "समायोजन",
          "notifications": "सूचनाएं",
          "requests": "अनुरोध",
          "Main": "मुख्य",
          "joinAs": "के रूप में शामिल",
          "Client": "ग्राहक",
          "Transporter": "Transporter",
          "CreateAnAccount": "खाता बनाएं",
          "Login": "लॉग इन करें",
          "AlreadyHaveAnAccount": "आप एक खाता है?",
          "fullName": "पूरा नाम",
          "mail": "ईमेल",
          "MobileNumber": "मोबाइल नंबर",
          "password": "पासवर्ड",
          "orRegisterWith": "या के साथ रजिस्टर करें",
          "ReceivingLocation": ": डिलिवरी का स्थान",
          "deliveryLocation": ": प्रसव का स्थान",
          "ChooseADate": "अपॉइंटमेंट चुनें",
          "DriverNotes": "ड्राइवर के नोट्स",
          "ApproximatePrice": "अनुमानित कीमत",
          "send": "भेजना",
          "bigTanker": "बड़ा टैंकर",
          "ChooseTheRightType": "सही प्रकार चुनें",
          "TrillGermanSides": "ट्रिल जर्मन पक्ष",
          "curtainTrill": "पर्दा ट्रिल",
          "TrailerGallab": "ट्रेलर Gallab",
          "TrillingHighSides": "ट्रिल हाई साइड",
          "trillItsSurface": "इसकी सतह को ट्रिल करें",
          "waterTrill": "वाटर ट्रिल",
          "CarTransportTrailer": "कार परिवहन ट्रेलर",
          "TrailerForTransportingSheepAndLivestock": "भेड़ और पशुओं के परिवहन के लिए ट्रेलर",
          "BradTrail": "ब्रैड ट्रेल",
          "waterTank": "पानी की टंकी",
          "AFuelTanker": "एक ईंधन टैंकर",
          "lorryTruck": "ठेला ट्रक",
          "closedTruck": "बंद ट्रक",
          "DumpTruck": "डंप ट्रक",
          "flatbedTruck": "समतल ट्रक",
          "OtherBigVector": "अन्य बड़े वेक्टर",
          "refrigeratorTruck": "रेफ्रिजरेटर ट्रक",
          "back": "पीछे",
          "name": "नाम",
          "number":"संख्या",
          "ContactTheDriver":"ड्राइवर को बुलाओ",
          "SuggestAnotherPrice":"एक और कीमत सुझाएं",
          "CancellingOrder":"रद्द करना",
          "AreYouSureToCancelTheOrder":"क्या आप वाकई ऑर्डर रद्द करना चाहते हैं",
          "no":"नहीं",
          "yes":"हां",
          "changeTheDriver":"ड्राइवर बदलें",
          "orderTracking":"आदेश ट्रैकिंग",
          "FileAComplaint":"एक शिकायत दर्ज़ करें",
          "TermsAndConditions":"नियम और शर्तें",
          "OtherOffers":"अन्य प्रस्ताव",
          "DearCustomer":"प्रिय ग्राहक",
          "YouCannotCancelTheOrderOrReplaceTheRepresentativeAfter7MinutesFromNow":"अब से 7 मिनट के बाद आप आदेश को रद्द नहीं कर सकते या प्रतिनिधि को बदल नहीं सकते",
          "Cancellation":"रद्द करना",
          "OK":"ठीक है",
          "Acceptance":"स्वीकार",
          "SuggestedPrice":"सुझाव कीमत",
          "adjustThePrice":"कीमत तय करें",
          "YourPriceHasBeenAccepted":"आपकी कीमत स्वीकार कर ली गई है",
          "GoToThePaymentStep":"आपकी कीमत स्वीकार कर ली गई है",
          "paying":"का भुगतान",
          "MyOrderDetails":" मेरे आदेश का विवरण",
          "NewApplicationPayAttentionToTheLocationOfDeliveryAndReceivingNewApplicationPayAttentionToTheSiteOfDeliveryAndReceiptNewApplicationPayAttentionToTheSiteOfDeliveryAndReceipt":"नया आवेदन वितरण और प्राप्त करने के स्थान पर ध्यान दें नया आवेदन वितरण और प्राप्ति की साइट पर ध्यान दें नया आवेदन वितरण और प्राप्ति की साइट पर ध्यान दें ",
          "IForgotTheSecretNumber":"मैं गुप्त नंबर भूल गया",
          "PleaseEnterYourMobileNumberTo":"कृपया अपना मोबाइल नंबर दर्ज करें",
          "LookingForATanker":"टैंकर की तलाश",
          "LargeTankertrucksAndTrailers":"बड़े टैंकर (ट्रक और ट्रेलर)",
          "MediumTankerDyna":"मध्यम टैंकर (दीना)",
          "SmallCarrierParcelsAndServices":"लघु वाहक (पार्सल और सेवाएं)",
          "SomeValuesEnteredAreEmptyPleaseMakeSureThatAllValuesAreEntered":"दर्ज किए गए कुछ मान खाली हैं। कृपया सुनिश्चित करें कि सभी मान दर्ज किए गए हैं",
          "Entry":"प्रवेश",
          "DontHaveAnAccount":"खाता नहीं है?",
          "orLoginWith":"या लॉगिन करें",
          "mediumTanker":"मध्यम टैंकर",
          "myBalance":"मेरा संतुलन",
          "AddCreditVia":"के माध्यम से क्रेडिट जोड़ें",
          "PreviousOrders":"पिछले आदेश",
          "currentOrders":"वर्तमान आदेश",
          "OrderDetails":"ऑर्डर का विवरण",
          "tracking":"नज़र रखना",
          "chat":"बात करना",
          "Contact":"संपर्क करना",
          "OrderNumber":"क्रम संख्या",
          "ARequestHasBeenSentFromTheDriver":"ड्राइवर से अनुरोध भेजा गया है",
          "YourOrderDetails":"आपके आदेश का विवरण",
          "PaymentDetails":"भुगतान विवरण",
          "cost":"लागत",
          "valueAddedTax":"15% वैट",
          "Total":"कुल",
          "DriverName":"चालक का नाम",
          "conveyorType":"कन्वेयर प्रकार",
          "ApproximateArrivalTime":": लगभग। आने का समय",
          "distance":" : दूरी",
          "VerifyPhoneNumber":"फ़ोन नंबर सत्यापित करें",
          "EnterTheCodeSentTo":"को भेजा गया कोड दर्ज करें",
          "addCoupon":"कूपन जोड़ें",
          "PaymentMethod":"भुगतान का तरीका",
          "AddACreditDebitCard":"क्रेडिट/डेबिट कार्ड जोड़ें",
          "cardNumber":"कार्ड नंबर",
          "ExpiryDateMonthYear":"समाप्ति तिथि        माह/वर्ष",
          "FirstName":"पहला नाम",
          "lastName":"उपनाम",
          "ourEnd":"!हमारा अंत",
          "PaymentConfirmedSuccessfully":"भुगतान की पुष्टि हो गई",
          "SaveTheCard":"कार्ड सेव करें",
          "addCard":"एक कार्ड जोड़ें +",
          "cash":"नकद",
          "Confirmation":"पुष्टीकरण",
          "paid":"भुगतान किया है",
          "writeYourMessage":"अपना संदेश लिखें",
          "NotPaid":"नहीं चुकाया",
          "writeyourMessage":"अपना संदेश लिखें",
          "ComplaintsAndSuggestions":"शिकायतें और सुझाव",
          "WriteYourComplaintOrSuggestions":"अपनी शिकायत या सुझाव लिखें",
          "WholesaleMerchandiseDelivery":"थोक माल वितरण",
          "FlowerDeliveryAndArrangement":"फूल वितरण और व्यवस्था",
          "MiscellaneousOther":"विविध / अन्य",
          "SweetsDelivery":"मिठाई वितरण",
          "ShareTheApp":"ऐप शेयर करें",
          "Exit":"बाहर निकलना",
          "LogOut":"लॉग आउट",
          "smallFridge":"छोटा फ्रिज",
          "closedVan":"बंद वैन",
          "PersonnelServices":"कार्मिक सेवाएं",
          "tank":"टैंक",
          "OtherSmallVectors":"अन्य छोटे वैक्टर",
          "AwaitingPayment":"भुगतान की प्रतीक्षा",
          "WriteYourProblemDetailsHere":"अपनी समस्या का विवरण यहां लिखें "
            "........................................"
            "..........................................."
            "..........................................."  "........................................"
            "..........................................."
            "..........................................." "..........................................."
            "................."  ".......",
          "attachments":"संलग्नक",
          "YouCanUploadPhotos":"आप 3 फोटो अपलोड कर सकते हैं"

        },
        "BD": {
          "YourRequestHasBeenSentToDrivers": "আমাদের অনুরোধ চালকদের কাছে পাঠানো হয়েছে",
          "Done": "সম্পন্ন",
          "MessageSentSuccessfully": "বার্তা সফলভাবে পাঠানো হয়েছে৷",
          "fail": "ব্যর্থ",
          "PleaseLoginAgain": "অনুগ্রহ পূর্বক আরো একবার প্রবেশ করুন",
          "Settings": "সেটিংস",
          "notifications": "বিজ্ঞপ্তি",
          "requests": "অনুরোধ",
          "Main": "প্রধান",
          "joinAs": "হিসাবে যোগদান করুন",
          "Client": "ক্লায়েন্ট",
          "Transporter": "পরিবহনকারী",
          "CreateAnAccount": "একটি অ্যাকাউন্ট তৈরি করুন",
          "Login": "প্রবেশ করুন",
          "AlreadyHaveAnAccount": "আপনি যদি একটি একাউন্ট আছে?",
          "fullName": "পুরো নাম",
          "mail": "ই-মেইল",
          "MobileNumber": "মোবাইল নম্বর",
          "password": "পাসওয়ার্ড",
          "orRegisterWith": "অথবা সাথে নিবন্ধন করুন",
          "ReceivingLocation": ": পৌঁছানোর স্থান",
          "deliveryLocation": ": ডেলিভারির ঠিকানা",
          "ChooseADate": "একটি অ্যাপয়েন্টমেন্ট চয়ন করুন",
          "DriverNotes": "ড্রাইভারের নোট",
          "ApproximatePrice": "আনুমানিক মূল্য",
          "send": "পাঠান",
          "bigTanker": "বড় ট্যাঙ্কার",
          "ChooseTheRightType": "সঠিক টাইপ নির্বাচন করুন",
          "TrillGermanSides": "ট্রিল জার্মান পক্ষ",
          "curtainTrill": "পর্দা ট্রিল",
          "TrailerGallab": "ট্রেলার গ্যালাব",
          "TrillingHighSides": "ট্রিল উচ্চ দিক",
          "trillItsSurface": "তার পৃষ্ঠ trill",
          "waterTrill": "জল ট্রিল",
          "CarTransportTrailer": "গাড়ি পরিবহন ট্রেলার",
          "TrailerForTransportingSheepAndLivestock": "ভেড়া এবং গবাদি পশু পরিবহনের জন্য ট্রেলার",
          "BradTrail": "ব্র্যাড ট্রেইল",
          "waterTank": "পানির ট্যাংক",
          "AFuelTanker": "একটি জ্বালানি ট্যাঙ্কার",
          "lorryTruck": "লরি ট্রাক",
          "closedTruck": "বন্ধ ট্রাক",
          "DumpTruck": "ডাম্প ট্রাক",
          "flatbedTruck": "ফ্ল্যাটবেড ট্রাক",
          "OtherBigVector": "অন্যান্য বড় ভেক্টর",
          "refrigeratorTruck": "রেফ্রিজারেটর ট্রাক",
          "back": "পেছনে",
          "name": "নাম",
          "number":"সংখ্যা",
          "ContactTheDriver":"ড্রাইভারকে ডাকো",
          "SuggestAnotherPrice":"অন্য মূল্য প্রস্তাব করুন",
          "CancellingOrder":"বাতিল করুন",
          "AreYouSureToCancelTheOrder":"আপনি অর্ডার বাতিল করতে নিশ্চিত",
          "no":"না",
          "yes":"হ্যাঁ",
          "changeTheDriver":"ড্রাইভার পরিবর্তন করুন",
          "orderTracking":"শৃঙ্খলা ট্র্যাকিং",
          "FileAComplaint":"একটি অভিযোগ দায়ের",
          "TermsAndConditions":"শর্তাবলী",
          "OtherOffers":"অন্যান্য অফার",
          "DearCustomer":"প্রিয় গ্রাহক",
          "YouCannotCancelTheOrderOrReplaceTheRepresentativeAfter7MinutesFromNow":"আপনি এখন থেকে 7 মিনিটের পরে অর্ডার বাতিল বা প্রতিনিধি প্রতিস্থাপন করতে পারবেন না",
          "Cancellation":"বাতিলকরণ",
          "OK":"ঠিক আছে",
          "Acceptance":"গ্রহণযোগ্যতা",
          "SuggestedPrice":"প্রস্তাবিত মূল্য",
          "adjustThePrice":"মূল্য নির্ধারণ করুন",
          "YourPriceHasBeenAccepted":"আপনার মূল্য গ্রহণ করা হয়েছে",
          "GoToThePaymentStep":"পেমেন্ট ধাপে যান",
          "paying":"পরিশোধ করা",
          "MyOrderDetails":" আমার অর্ডার বিবরণ",
          "NewApplicationPayAttentionToTheLocationOfDeliveryAndReceivingNewApplicationPayAttentionToTheSiteOfDeliveryAndReceiptNewApplicationPayAttentionToTheSiteOfDeliveryAndReceipt":"নতুন অ্যাপ্লিকেশন ডেলিভারি এবং প্রাপ্তির অবস্থানে মনোযোগ দিন নতুন অ্যাপ্লিকেশন ডেলিভারি এবং প্রাপ্তির সাইটে মনোযোগ দিন নতুন অ্যাপ্লিকেশন ডেলিভারি এবং প্রাপ্তির সাইটে মনোযোগ দিন ",
          "IForgotTheSecretNumber":"গোপন নম্বর ভুলে গেছি",
          "PleaseEnterYourMobileNumberTo":"আপনার মোবাইল নম্বর লিখুন",
          "LookingForATanker":"ট্যাঙ্কার খুঁজছি",
          "LargeTankertrucksAndTrailers":"বড় ট্যাঙ্কার (ট্রাক এবং ট্রেলার)",
          "MediumTankerDyna":"মাঝারি ট্যাঙ্কার (দিনা)",
          "SmallCarrierParcelsAndServices":"ছোট ক্যারিয়ার (পার্সেল এবং পরিষেবা)",
          "SomeValuesEnteredAreEmptyPleaseMakeSureThatAllValuesAreEntered":"প্রবেশ করা কিছু মান খালি। অনুগ্রহ করে নিশ্চিত করুন যে সমস্ত মান প্রবেশ করানো হয়েছে",
          "Entry":"এন্ট্রি",
          "DontHaveAnAccount":"একটি অ্যাকাউন্ট নেই?",
          "orLoginWith":"অথবা লগইন করুন",
          "mediumTanker":"মাঝারি ট্যাঙ্কার",
          "myBalance":"আমার ব্যালেন্স",
          "AddCreditVia":"মাধ্যমে ক্রেডিট যোগ করুন",
          "PreviousOrders":"পূর্ববর্তী আদেশ",
          "currentOrders":"বর্তমান আদেশ",
          "OrderDetails":"আদেশ বিবরণী",
          "tracking":"ট্র্যাকিং",
          "chat":"চ্যাট",
          "Contact":"যোগাযোগ",
          "OrderNumber":"অর্ডার নম্বর",
          "ARequestHasBeenSentFromTheDriver":"চালকের কাছ থেকে একটি অনুরোধ পাঠানো হয়েছে",
          "YourOrderDetails":"আপনার অর্ডার বিবরণ",
          "PaymentDetails":"পেমেন্ট বিবরণ",
          "cost":"খরচ",
          "valueAddedTax":"15% ভ্যাট",
          "Total":"মোট",
          "DriverName":"ড্রাইভারের নাম",
          "conveyorType":"পরিবাহক প্রকার",
          "ApproximateArrivalTime":": প্রায়. আগমনের সময়",
          "distance":" : দূরত্ব",
          "VerifyPhoneNumber":"ফোন নম্বর যাচাই করুন",
          "EnterTheCodeSentTo":"প্রেরিত কোড লিখুন",
          "addCoupon":"কুপন যোগ করুন",
          "PaymentMethod":"মূল্যপরিশোধ পদ্ধতি",
          "AddACreditDebitCard":"একটি ক্রেডিট/ডেবিট কার্ড যোগ করুন",
          "cardNumber":"কার্ড নম্বর",
          "ExpiryDateMonthYear":"মেয়াদ শেষ হওয়ার তারিখ মাস/বছর",
          "FirstName":"নামের প্রথম অংশ",
          "lastName":"নামের শেষাংশ",
          "ourEnd":"!আমাদের শেষ",
          "PaymentConfirmedSuccessfully":"পেমেন্ট সফলভাবে নিশ্চিত করা হয়েছে",
          "SaveTheCard":"কার্ডটি সংরক্ষণ করুন",
          "addCard":"একটি কার্ড + যোগ করুন",
          "cash":"নগদ",
          "Confirmation":"নিশ্চিতকরণ",
          "paid":"পরিশোধ করা",
          "writeYourMessage":"আপনার বার্তা লিখুন",
          "NotPaid":"টাকা দেওয়া হয়নি",
          "writeyourMessage":"আপনার বার্তা লিখুন",
          "ComplaintsAndSuggestions":"অভিযোগ এবং পরামর্শ",
          "WriteYourComplaintOrSuggestions":"আপনার অভিযোগ বা পরামর্শ লিখুন",
          "WholesaleMerchandiseDelivery":"পাইকারি পণ্য সরবরাহ",
          "FlowerDeliveryAndArrangement":"ফুল বিতরণ এবং ব্যবস্থা",
          "MiscellaneousOther":"বিবিধ/অন্যান্য",
          "SweetsDelivery":"মিষ্টি বিতরণ",
          "ShareTheApp":"অ্যাপটি শেয়ার করুন",
          "Exit":"প্রস্থান করুন",
          "LogOut":"প্রস্থান",
          "smallFridge":"ছোট ফ্রিজ",
          "closedVan":"বন্ধ ভ্যান",
          "PersonnelServices":"কর্মী সেবা",
          "tank":"ট্যাঙ্ক",
          "OtherSmallVectors":"অন্যান্য ছোট ভেক্টর",
          "AwaitingPayment":"পেমেন্ট অপেক্ষা",
          "WriteYourProblemDetailsHere":"এখানে আপনার সমস্যার বিবরণ লিখুন "
            "........................................"
            "..........................................."
            "..........................................."  "........................................"
            "..........................................."
            "..........................................." "..........................................."
            "................."  ".......",
          "attachments":"সংযুক্তি",
          "YouCanUploadPhotos":"আপনি 3টি ছবি আপলোড করতে পারেন"
        },
        "urd": {
          "YourRequestHasBeenSentToDrivers": "آپ کی درخواست ڈرائیوروں کو بھیج دی گئی ہے۔",
          "Done": "ہو گیا",
          "MessageSentSuccessfully": "پیغام کامیابی سے چلا گیا",
          "fail": "ناکام",
          "PleaseLoginAgain": "براہ کرم دوبارہ لاگ ان کریں۔",
          "Settings": "ترتیبات",
          "notifications": "اطلاعات",
          "requests": "درخواستیں",
          "Main": "مرکزی",
          "joinAs": "کے طور پر شامل ہوں",
          "Client": "کلائنٹ",
          "Transporter": "ٹرانسپورٹر",
          "CreateAnAccount": "کھاتا کھولیں",
          "Login": "لاگ ان کریں",
          "AlreadyHaveAnAccount": "کیا آپ کا اکاؤنٹ ہے؟",
          "fullName": "پورا نام",
          "mail": "ای میل",
          "MobileNumber": "موبائل نمبر",
          "password": "پاس ورڈ",
          "orRegisterWith": "یا کے ساتھ رجسٹر کریں",
          "ReceivingLocation": ": ترسیل کی جگہ",
          "deliveryLocation": ": ترسیل کی جگہ",
          "ChooseADate": "ملاقات کا وقت منتخب کریں۔",
          "DriverNotes": "ڈرائیور کے نوٹس",
          "ApproximatePrice": "تخمینی قیمت",
          "send": "بھیجیں",
          "bigTanker": "بڑا ٹینکر",
          "ChooseTheRightType": "صحیح قسم کا انتخاب کریں۔",
          "TrillGermanSides": "ٹریل جرمن اطراف",
          "curtainTrill": "پردہ ٹریل",
          "TrailerGallab": "ٹریلر گیلب",
          "TrillingHighSides": "ٹریل اونچے اطراف",
          "trillItsSurface": "اس کی سطح کو ٹریل کریں۔",
          "waterTrill": "پانی ٹرل",
          "CarTransportTrailer": "کار ٹرانسپورٹ ٹریلر",
          "TrailerForTransportingSheepAndLivestock": "بھیڑوں اور مویشیوں کی نقل و حمل کے لیے ٹریلر",
          "BradTrail": "بریڈ ٹریل",
          "waterTank": "پانی کے ٹینک",
          "AFuelTanker": "ایندھن کا ٹینکر",
          "lorryTruck": "لاری ٹرک",
          "closedTruck": "بند ٹرک",
          "DumpTruck": "ڈمپ ٹرک",
          "flatbedTruck": "فلیٹ بیڈ ٹرک",
          "OtherBigVector": "دوسرے بڑے ویکٹر",
          "refrigeratorTruck": "ریفریجریٹر ٹرک",
          "back": "پیچھے",
          "name": "نام",
          "number":"نمبر",
          "ContactTheDriver":"ڈرائیور کو بلاؤ",
          "SuggestAnotherPrice":"کوئی اور قیمت تجویز کریں۔",
          "CancellingOrder":"منسوخ کریں۔",
          "AreYouSureToCancelTheOrder":"کیا آپ یقینی طور پر آرڈر منسوخ کر رہے ہیں؟",
          "no":"نہیں",
          "yes":"جی ہاں",
          "changeTheDriver":"ڈرائیور کو تبدیل کریں",
          "orderTracking":"آرڈر ٹریکنگ",
          "FileAComplaint":"شکایت درج کروائیں۔",
          "TermsAndConditions":"شرائط و ضوابط",
          "OtherOffers":"دیگر پیشکشیں",
          "DearCustomer":"معزز صارف",
          "YouCannotCancelTheOrderOrReplaceTheRepresentativeAfter7MinutesFromNow":"آپ اب سے 7 منٹ کے بعد آرڈر منسوخ یا نمائندے کی جگہ نہیں لے سکتے",
          "Cancellation":"منسوخی",
          "OK":"ٹھیک ہے",
          "Acceptance":"قبولیت",
          "SuggestedPrice":"تجویز کردہ قیمت",
          "adjustThePrice":"قیمت مقرر کریں۔",
          "YourPriceHasBeenAccepted":"آپ کی قیمت قبول کر لی گئی ہے۔",
          "GoToThePaymentStep":"ادائیگی کے مرحلے پر جائیں۔",
          "paying":"ادائیگی",
          "MyOrderDetails":" میرے آرڈر کی تفصیلات",
          "NewApplicationPayAttentionToTheLocationOfDeliveryAndReceivingNewApplicationPayAttentionToTheSiteOfDeliveryAndReceiptNewApplicationPayAttentionToTheSiteOfDeliveryAndReceipt":"نئی ایپلیکیشن ڈیلیوری اور وصول کرنے کے مقام پر توجہ دیں نئی ایپلیکیشن ڈیلیوری اور رسید کی جگہ پر توجہ دیں نئی ایپلیکیشن ڈیلیوری اور رسید کی جگہ پر توجہ دیں ",
          "IForgotTheSecretNumber":"میں خفیہ نمبر بھول گیا۔",
          "PleaseEnterYourMobileNumberTo":"براہ کرم اپنا موبائل نمبر درج کریں۔",
          "LookingForATanker":"ٹینکر کی تلاش ہے۔",
          "LargeTankertrucksAndTrailers":"بڑا ٹینکر (ٹرک اور ٹریلر)",
          "MediumTankerDyna":"درمیانے درجے کا ٹینکر (دینا)",
          "SmallCarrierParcelsAndServices":"چھوٹا کیریئر (پارسل اور خدمات)",
          "SomeValuesEnteredAreEmptyPleaseMakeSureThatAllValuesAreEntered":"درج کردہ کچھ قدریں خالی ہیں۔ براہ کرم یقینی بنائیں کہ تمام اقدار درج ہیں۔",
          "Entry":"داخلہ",
          "DontHaveAnAccount":"اکاؤنٹ نہیں ہے؟",
          "orLoginWith":"یا لاگ ان کریں۔",
          "mediumTanker":"درمیانے درجے کا ٹینکر",
          "myBalance":"میرا بیلنس",
          "AddCreditVia":"کے ذریعے کریڈٹ شامل کریں۔",
          "PreviousOrders":"پچھلے احکامات",
          "currentOrders":"موجودہ احکامات",
          "OrderDetails":"آرڈر کی تفصیلات",
          "tracking":"ٹریکنگ",
          "chat":"چیٹ",
          "Contact":"رابطہ کریں۔",
          "OrderNumber":"آرڈر نمبر",
          "ARequestHasBeenSentFromTheDriver":"ڈرائیور کی طرف سے درخواست بھیجی گئی ہے۔",
          "YourOrderDetails":"آپ کے آرڈر کی تفصیلات",
          "PaymentDetails":"ادائیگی کی تفصیلات",
          "cost":"لاگت",
          "valueAddedTax":"15% VAT",
          "Total":"کل",
          "DriverName":"ڈرائیور کا نام",
          "conveyorType":"کنویئر کی قسم",
          "ApproximateArrivalTime":": تقریبا. آمد کے وقت",
          "distance":" : فاصلے",
          "VerifyPhoneNumber":"فون نمبر کی تصدیق کریں۔",
          "EnterTheCodeSentTo":"بھیجے گئے کوڈ کو درج کریں۔",
          "addCoupon":"کوپن شامل کریں",
          "PaymentMethod":"ادائیگی کا طریقہ",
          "AddACreditDebitCard":"کریڈٹ/ڈیبٹ کارڈ شامل کریں۔",
          "cardNumber":"کارڈ نمبر",
          "ExpiryDateMonthYear":"میعاد ختم ہونے کی تاریخ مہینہ/سال",
          "FirstName":"پہلا نام",
          "lastName":"آخری نام",
          "ourEnd":"!ہمارا خاتمہ",
          "PaymentConfirmedSuccessfully":"ادائیگی کامیابی سے تصدیق ہو گئی۔",
          "SaveTheCard":"کارڈ کو محفوظ کریں۔",
          "addCard":"ایک کارڈ + شامل کریں۔",
          "cash":"نقد",
          "Confirmation":"تصدیق",
          "paid":"ادا کیا",
          "writeYourMessage":"اپنا پیغام لکھیں",
          "NotPaid":"ادا نہیں کیا",
          "writeyourMessage":"اپنا پیغام لکھیں",
          "ComplaintsAndSuggestions":"شکایات اور تجاویز",
          "WriteYourComplaintOrSuggestions":"اپنی شکایت یا تجاویز لکھیں۔",
          "WholesaleMerchandiseDelivery":"ہول سیل تجارتی سامان کی ترسیل",
          "FlowerDeliveryAndArrangement":"پھولوں کی ترسیل اور انتظام",
          "MiscellaneousOther":"متفرق/دیگر",
          "SweetsDelivery":"مٹھائی کی ترسیل",
          "ShareTheApp":"ایپ کا اشتراک کریں۔",
          "Exit":"باہر نکلیں",
          "LogOut":"لاگ آوٹ",
          "smallFridge":"چھوٹا فریج",
          "closedVan":"بند وین",
          "PersonnelServices":"پرسنل سروسز",
          "tank":"ٹینک",
          "OtherSmallVectors":"دوسرے چھوٹے ویکٹر",
          "AwaitingPayment":"ادائیگی کے منتظر",
          "WriteYourProblemDetailsHere":"اپنے مسئلے کی تفصیلات یہاں لکھیں۔ "
            "........................................"
            "..........................................."
            "..........................................."  "........................................"
            "..........................................."
            "..........................................." "..........................................."
            "................."  ".......",
          "attachments":"منسلکات",
          "YouCanUploadPhotos":"آپ 3 تصاویر اپ لوڈ کر سکتے ہیں۔"
        },
      };
}
